CREATE TABLE usuario (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome           VARCHAR(150) NOT NULL,
    login          VARCHAR(100) NOT NULL,
    email          VARCHAR(150) NOT NULL,
    senha_hash     VARCHAR(100) NOT NULL,
    perfil         VARCHAR(20)  NOT NULL CHECK (perfil IN ('LEITOR', 'TECNICO', 'ADMIN', 'SUPERADMIN')),
    status         VARCHAR(20)  NOT NULL DEFAULT 'ATIVO' CHECK (status IN ('ATIVO', 'BLOQUEADO', 'EXCLUIDO')),
    trocar_senha   BOOLEAN      NOT NULL DEFAULT TRUE,
    criado_em      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    atualizado_em  TIMESTAMPTZ  NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX ux_usuario_login ON usuario (lower(login));
CREATE UNIQUE INDEX ux_usuario_email ON usuario (lower(email));

CREATE TABLE instituicao (
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome  VARCHAR(50)  NOT NULL UNIQUE,
    logo  VARCHAR(150)
);

CREATE TABLE unidade (
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome    VARCHAR(100) NOT NULL UNIQUE,
    imagem  VARCHAR(150)
);

CREATE TABLE unidade_instituicao (
    unidade_id      BIGINT NOT NULL REFERENCES unidade (id),
    instituicao_id  BIGINT NOT NULL REFERENCES instituicao (id),
    PRIMARY KEY (unidade_id, instituicao_id)
);

CREATE TABLE transferencia (
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data                     DATE         NOT NULL,
    motivo                   VARCHAR(30)  NOT NULL CHECK (motivo IN
                                 ('TRANSFERENCIA_ENTRE_FILIAIS', 'BAIXA_DESCARTE', 'MANUTENCAO', 'EMPRESTIMO_TEMPORARIO')),
    instituicao_id           BIGINT       NOT NULL REFERENCES instituicao (id),
    origem_id                BIGINT       NOT NULL REFERENCES unidade (id),
    destino_id               BIGINT       NOT NULL REFERENCES unidade (id),
    responsavel_envio        VARCHAR(150) NOT NULL,
    responsavel_recebimento  VARCHAR(150) NOT NULL,
    criado_por_id            BIGINT       NOT NULL REFERENCES usuario (id),
    criado_em                TIMESTAMPTZ  NOT NULL DEFAULT now(),
    atualizado_em            TIMESTAMPTZ  NOT NULL DEFAULT now(),
    excluido_em              TIMESTAMPTZ
);
CREATE INDEX ix_transferencia_data ON transferencia (data);
CREATE INDEX ix_transferencia_criado_por ON transferencia (criado_por_id);
CREATE INDEX ix_transferencia_origem ON transferencia (origem_id);
CREATE INDEX ix_transferencia_destino ON transferencia (destino_id);

CREATE TABLE item (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transferencia_id  BIGINT       NOT NULL REFERENCES transferencia (id) ON DELETE CASCADE,
    ordem             SMALLINT     NOT NULL,
    descricao         VARCHAR(200) NOT NULL,
    patrimonio        VARCHAR(150),
    observacao        TEXT
);
CREATE INDEX ix_item_transferencia ON item (transferencia_id);
CREATE INDEX ix_item_patrimonio ON item (patrimonio);
