-- Controle de Saída de Materiais da Unidade (formulário FM-072-UOP-04): modalidade mais simples que o termo de
-- transferência, sem patrimônio nos itens. Ver docs/modelo-de-dados.md e docs/decisoes.md (D-044).

CREATE TABLE saida_material (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data             DATE         NOT NULL,
    tipo             VARCHAR(20)  NOT NULL
                     CHECK (tipo IN ('PERMANENTE', 'TEMPORARIO', 'MANUTENCAO', 'EVENTO', 'OUTRO')),
    -- Preenchido só quando tipo = OUTRO ("Outro, qual: ...")
    tipo_outro       VARCHAR(150),
    instituicao_id   BIGINT       NOT NULL REFERENCES instituicao (id),
    origem_id        BIGINT       NOT NULL REFERENCES unidade (id),
    -- Destino: uma unidade cadastrada OU um destino externo (assistência técnica, local de evento...)
    destino_id       BIGINT       REFERENCES unidade (id),
    destino_externo  VARCHAR(200),
    -- Nome impresso sob a linha "Assinatura do Portador do Equipamento" (opcional)
    portador         VARCHAR(150),
    criado_por_id    BIGINT       NOT NULL REFERENCES usuario (id),
    criado_em        TIMESTAMPTZ  NOT NULL DEFAULT now(),
    atualizado_em    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    excluido_em      TIMESTAMPTZ,
    CONSTRAINT ck_saida_destino CHECK ((destino_id IS NULL) <> (destino_externo IS NULL)),
    CONSTRAINT ck_saida_tipo_outro CHECK ((tipo = 'OUTRO') = (tipo_outro IS NOT NULL))
);
CREATE INDEX ix_saida_material_data ON saida_material (data);
CREATE INDEX ix_saida_material_criado_por ON saida_material (criado_por_id);
CREATE INDEX ix_saida_material_origem ON saida_material (origem_id);
CREATE INDEX ix_saida_material_destino ON saida_material (destino_id);

CREATE TABLE saida_material_item (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    saida_id       BIGINT       NOT NULL REFERENCES saida_material (id) ON DELETE CASCADE,
    ordem          SMALLINT     NOT NULL,
    descricao      VARCHAR(200) NOT NULL,
    -- Setor, oficina ou laboratório
    area_saida     VARCHAR(150),
    area_entrada   VARCHAR(150),
    observacao     TEXT
);
CREATE INDEX ix_saida_material_item_saida ON saida_material_item (saida_id);
